# Generated by Django 5.1.2 on 2024-10-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("calories", models.PositiveIntegerField()),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-date_posted"],
            },
        ),
    ]
